.gitignore
docker/srcs/uwsgi-django/django-entrypoint.sh

❗️❗️実行ください: git rm -r --cached docker/srcs/uwsgi-django/static

❗️❗️static/を再度gitignoreしました。理由: entrypoint.shで自動収集を設定(Djangoの機能として用意されていた)

---

Makefile

makefileにmigrate用のターゲットを追加しました。
（DB修正時に毎回行う必要がある）
理由: account/のmigrateがentrypoint.shでは正常に動作しなかったため。
```
migrate_Django_db:
docker exec -it uwsgi-django bash -c "python manage.py migrate --noinput"
```

Makefile target🎯[add]migrate_Django_db:

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/online-status.js
docker/srcs/uwsgi-django/trans_pj/tests/test_friend.py

#109 
<br>
memo
- SPA統合、SPA Testがopenのため、`add-spa-test` をbranch元、merge先としています
- close状況次第でbranch元, merge先を変更します

[fix] friend pageのfriend nameのリンクを/app/ URLに修正

---

.github/workflows/e2e_test.yml
docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/templates/chat/dm_sessions.html
docker/srcs/uwsgi-django/chat/urls_api.py
docker/srcs/uwsgi-django/chat/views/views.py
docker/srcs/uwsgi-django/trans_pj/tests/test_dm.py

#113 
- StartDMで不正なnicknameを入力した時、/dm/に戻らず/dm-with/nickname/に留まる点を修正
- Start With nickname入力テストを追加
<br>
残課題（別issue）
- StartDMの遷移がDOM更新でSPA遷移になっていない

[fix] SPA DM

---

.github/workflows/e2e_test.yml
docker/srcs/uwsgi-django/accounts/models.py
docker/srcs/uwsgi-django/chat/static/chat/js/dm-with-user.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/ui-util.js
docker/srcs/uwsgi-django/trans_pj/tests/test_basic_auth.py
docker/srcs/uwsgi-django/trans_pj/tests/test_profile.py

#114 
IME変換確定のリターンで送信される現象を修正
<br>
残課題
- Sendクリックで空文字列を送信できる #141

[fix] input formへの全角入力

---

docker/srcs/uwsgi-django/accounts/models.py
docker/srcs/uwsgi-django/accounts/tests/test_signup.py
docker/srcs/uwsgi-django/accounts/tests/test_user_profile.py
docker/srcs/uwsgi-django/trans_pj/tests/test_basic_auth.py
docker/srcs/uwsgi-django/trans_pj/tests/test_dm.py
docker/srcs/uwsgi-django/trans_pj/tests/test_profile.py

#140 
- min: 8: settings.py AUTH_PASSWORD_VALIDATORSで設定済み
-  max: accounts/models.py kNICKNAME_MAX_LENGTH=30で設定済み

[update] nickname, password, emailの最大・最小文字数

---

docker/srcs/uwsgi-django/trans_pj/tests/__init__.py

ちょくちょく失敗しているので再修正を...
基本的に`_create_new_user()`でemail input formが見つからずtimeoutしている模様
Re-runするとpassすることも
https://github.com/42trans/ft_transcendence/actions/runs/9394801153/job/25874607054#step:9:21
```
Traceback (most recent call last):
File "/code/trans_pj/tests/test_2fa.py", line 13, in setUp
self._create_new_user(email=self.email,
File "/code/trans_pj/tests/__init__.py", line 333, in _create_new_user
self._send_to_elem(By.ID, "password1", password)
File "/code/trans_pj/tests/__init__.py", line 217, in _send_to_elem
elem = wait.until(EC.presence_of_element_located((by, elem_value)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
raise TimeoutException(message, screen, …
```

[fix] E2Eテスト _create_new_user()のfail対策

---

docker/srcs/uwsgi-django/chat/static/chat/js/module/setup-dm-websocket.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/ui-util.js

#141 
`handleSendMessage()`で、Enter, Clickともに空文字列の送信を制御するように変更

[fix] DM sendボタンで空文字列を送信不可に修正

---

Makefile
docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateBaseRound.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/routeTable.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/GameMatch.js
docker/srcs/uwsgi-django/trans_pj/static/spa/json/urlConfig.json

#138 
ページ遷移の際、DOM全体の更新となり、SPA遷移になっていない点を修正
<br>
3DのStartMatchボタンのhref変更のついでに...
Makefile `build_up_default`でvite buildし`/static/pong/three/` へ3Dの変更を確実に反映するようにしました

[fix] SPA遷移

---

docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/pong/static/pong/css/hth-dm.css
docker/srcs/uwsgi-django/pong/static/pong/css/hth-tournament.css
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentCreator.js
docker/srcs/uwsgi-django/trans_pj/templates/spa.html

#163
ついでにDMにテーマ適用
---
DMのシャドウがぼやけて見えない
同じくtournament新規作成も微妙。OKだけど。loginと同じシャドウオフにするのがベスト
どちらも.hth-containerの継承なので、影響考慮し、上書きする形の修正が望ましい

みづらいドロップシャドウを修正 dm, tournament-create

---

docker/srcs/uwsgi-django/accounts/views/user.py
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/pong/views/navi_views.py
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_2fa.py
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

#168 
全URLへの直接アクセス時の挙動を評価 
- リンクを貼っていなくとも、URLコピペで移動できるため、念のために確認しておく
- 要認証ページではguestをloginにリダイレクト
- login済みuserはlogin -> /app/にリダイレクト
- ... などの挙動を確認
<br>
- guest, user(2fa on/off)の3パターンを検証
- `-`はURL通りの遷移
- `/url/`はリダイレクト先 page
-  `o`でpage, urlともに移動
- `△`でpageのみ移動, urlはリダイレクト前のまま
- `:nickname`は`user2`で検証 
| access url                                      | guest                      | user (2fa off )| user (2fa on) | 
|---------------------------------|-----------------------|----------|---------|
| /app/                                               |  -                                   |  -             |  -            |  
| /app/home/                                     |  -                                   |  -            |  -             | 
| /app/game/tournament/                | `o …

[E2E Test] 全URLへの直接アクセス時の挙動を評価

---

docker/srcs/compose-yaml/compose-web.yaml
docker/srcs/uwsgi-django/pong/static/pong/css/hth-main.css
docker/srcs/uwsgi-django/pong/templates/pong/play-tournament.html
docker/srcs/uwsgi-django/pong/templates/pong/pong-online.html
docker/srcs/vite/pong-three/src/js/PongApp.js
docker/srcs/vite/pong-three/src/js/config/PongEngineConfig.js
docker/srcs/vite/pong-three/src/js/effect/ZoomTable.js
docker/srcs/vite/pong-three/src/js/manager/AllScenesManager.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngine.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineInit.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineUpdate.js
docker/srcs/vite/pong-three/src/js/state/GamePlayState.js

#169
All Device:最初の描画がウィンドウサイズからはみ出てしまう件
ゲームテーブルだけズーム（カメラ位置）をウインドウサイズで別判定　=> オーラ球は画面いっぱいに描画されるキャンバスサイズ判定
テーブルの読み込みは状態パターンの遷移で遅れて行われるので、その行でリサイズ発火 (App.init()ではなく、ChangeState後のGameScene.entry()の位置)
アニメーションに使用されるパラメータをウィンドウサイズ起点での計算に変更
修正したバグ:
サーブボールのリセット時方向 self.ball["direction"]["y"] = random.uniform(-0.5, 0.5)
サーブボールの開始タイミングを少し遅らせる await asyncio.sleep(1)
最初の描画がウィンドウサイズからはみ出る。
リロード時、終了した試合がリセットされてしまう

3D-ballServe-#169

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/accounts/templates/verify/verify_2fa.html
docker/srcs/uwsgi-django/accounts/views/two_factor_auth.py
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/views/navi_views.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Verify2FA.js
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

- guest userのリダイレクト挙動を修正
- login -> tournamentからブラウザバックで再度tournamentへ遷移するループを解除 #170 
- `access-url` -> `login`へリダイレクト(urlはaccess-urlのまま) -> `access-url`への遷移挙動を追加
<br>
- ※ ~`/before-redirect/` への遷移を確認することは面倒なので、 login pageに居ないことを評価~
- 手動テストのコストを考慮し、全ページの代表要素を取得し、期待するページを表示中であることを評価するassertを追加した  fe50276
<br>
- 2fa認証の際、login -> verify2faへブラウザurl(リダイレクト元のurl)が引き継がれないためquery parameterを追加。verify 2fa後にリダイレクト元を表示できるように。 137393e
- `https://localhost/app/auth/verify-2fa/?next=/app/user/game-history/`の直接アクセスや、リロードでquery stringが消えていた -> 対策済み  19e23e0
- `https://localhost/app/auth/verify-2fa/?next=/app/auth/verify-2fa/`のようにnextがcurrentと一致している場合にはnextをクリア  2924a84
<br>
- `/spa/js/login.js` で `setupLoginEventListener` の呼び出しを追加しています  76082e0
- `/login/`へのリダイレクトはdjango viewで直接ページをレンダリングしているため、SPA遷移ではない …

[fix] guest userのリダイレクト

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/logout.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/updateHeader.js
docker/srcs/uwsgi-django/trans_pj/urls.py
docker/srcs/uwsgi-django/trans_pj/views/main_views.py
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineMatch.js

#180 
#182 のベースから開始
コミット可視化のため merge先を`fix-#182`で進めていますが、`dev`へmerge予定です
<br>
* Your website must be a [single-page application](https://en.wikipedia.org/wiki/Single-page_application).
* The user should be able to use the Back and Forward buttons of the browser.
<br>
* 単一のWebページのみから構成する
* 必要なコード（HTML、JavaScript、CSS）は最初にまとめて読み込むか、ユーザの操作などに応じて動的にサーバと通信し、必要なものだけ読み込みを行う
<br>
<br>
- Auth
- ページ遷移のSPA化だけでは、naviがGuest/User向けに更新されない。naviの部分的な更新を追加 a6ca5c0
- 42authは認証フロー上、一時的にSPA外れる
- 42認証サーバーへのリダイレクト、パラメータ受け取り用の`/oauth-ft/callback/`へのリダイレクトが発生
- OAuth部分をpopupなどで処理し、ブラウザでSPAを維持することも可能そうだが、以下理由により優先度低め（余裕があればやりたい... )
- 現状でSPA要件は満足していると思われる（OAuthで外部サーバーにアクセスし、SPA外れるのはOAuthの仕様[1]であり、SPA要件を上書きするはず）
- ポップアップでOAuthを走らせる場合、SPAを開いているブラウザ側との連携が発生し、考慮すべき問題が増える
- 3D Pong
- …

[subject] SPA

---

docker/srcs/uwsgi-django/accounts/tests/test_is_user.py
docker/srcs/uwsgi-django/accounts/urls_api.py
docker/srcs/uwsgi-django/accounts/views/is_user.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/isUser.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/user.js

- login済みuserが`/auth/*/`へアクセスすると、画面表示は`/app/`へ更新されるが、URLは`/auth/*/`のまま（URLと表示内容の不整合）
- これは、django view関数でリダイレクト & レンダリングしており画面は更新されるが、JSの`switchPage()`を呼んでいないためURLを制御できていないことが原因 -> JSでのURL制御を追加
<br>
- before: login後`/auth/*/`へアクセス -> URL`/auth/*/`のままTOP画面に遷移
- after: login後`/auth/*/`へアクセス -> URL`/app/`でTOP画面に遷移
<br>
- リンククリックイベントの際、`/spa/js/index.js`内でlogin userが`/app/`リダイレクトされるページであればurlを`/app/`に差し替えることで対応  bc159a3
<br>
- まだツメ甘いところがありますが、dev集約に回します
- login後、ブラウザバックで`/auth/*/`に戻ると、URLは`/auth/*/`で表示はTOP #191

[fix] login userのリダイレクトURL制御

---

docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

PR #130 で追加された以下のアラートに対応
https://github.com/42trans/ft_transcendence/blob/d3c64ae34905eaf50ad5dfa33e7ef104dfde4e72/docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/UserManager.js#L43-L46
<br>
- before (init): E2E Test ❌ 404bc59
- after (commit後): E2E Test ✅ 733df25

[fix] E2E test: GuestでTournamentを開いた際のalert処理を追加

---

docker/srcs/uwsgi-django/accounts/models.py
docker/srcs/uwsgi-django/pong/models.py
docker/srcs/uwsgi-django/pong/views/tournament_views.py
docker/srcs/uwsgi-django/trans_pj/settings.py
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_basic_auth.py
docker/srcs/uwsgi-django/trans_pj/tests/test_profile.py
docker/srcs/uwsgi-django/trans_pj/tests/test_tournament.py

#183 
input周りの仕様、コーナーケースを再確認し、不足があれば変更＆テスト追加
<br>
- E2Eテスト追加
- 文字数、文字種、XSSの不足分を追加
- Tournament name, player namesのテストを追加
- 登録上限数を仮決め（雑に決めただけ、少なくても良い気がしています）
- user 10000
- tournament 10000
- tournament
- tournament name, player nameの文字数、文字種見直し
- tournament create エラーメッセージ整形
<br>
<br>
- avatar画像のfilenameに全角や特殊記号が含まれている場合、`_`に置換され`media`に格納される
- user登録上限を超過（設定数6でテスト）
- tournament登録数超過した場合（設定数2でテスト）
- tournament nameの重複排除すると、APIのテストが落ちたため重複OKのまま。開催中のtournament名との重複排除は必要？とも思ったが、Offline Tournamentなので気にする必要はなさそう

[check] input周りのコーナーケース再確認

---

.github/workflows/e2e_test.yml
docker/srcs/uwsgi-django/accounts/static/accounts/js/block-user.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/disable_2fa.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/edit_profile.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/enable_2fa.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/friend.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/unblock-user.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/upload-avatar.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/userProfile.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/accounts/templates/accounts/plane/edit_profile.html
docker/srcs/uwsgi-django/accounts/tests/test_jwt.py
docker/srcs/uwsgi-django/accounts/urls.py
docker/srcs/uwsgi-django/accounts/urls_api.py
docker/srcs/uwsgi-django/accounts/views/friend.py
docker/srcs/uwsgi-django/accounts/views/jwt.py
docker/srcs/uwsgi-django/accounts/views/two_factor_auth.py
docker/srcs/uwsgi-django/accounts/views/user.py
docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/static/chat/js/test-system-message.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentCreator.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentDeleter.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentOverview.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/UserManager.js
docker/srcs/uwsgi-django/trans_pj/settings.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/isUser.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/refreshJWT.js

#177 
JWTの有効性、期限、client側の格納方法などを再確認 & リファクタリングなど
<br>
- user情報を元に秘密鍵で署名されたJson形式のtoken(Acess-Token, Refresh-Token)を生成
https://github.com/42trans/ft_transcendence/blob/620abe595aa6947bfc7d22d75a096a164bd2cd30/docker/srcs/uwsgi-django/accounts/views/jwt.py#L19-L25
- Acess-Token, Refresh-Tokenをuserが保持し、serverはそのtokenを検証することでuserのlogin状態を評価することが可能。serverはuserのlogin状態を記録する必要がない、ステートレスな認証システムとなる
- Access-Tokenで認証を管理、Refresh-Tokenは有効期限延長用
- 有効期限
- Access-Token < Refresh-Tokenであることが一般的
- Access-Token期限切れでも、有効なRefresh-Tokenを保持しているclientに対し、serverは有効なAccess-Token( & Refresh-Token)を再発行する
- Refresh-Token有効期限内にアクセスがなければ、認証は解除される
<br>
- セキュリティ面を考慮し、access token, refresh tokenの有効期間 -> [2-1 継続使用しない（無効化する）& 有効期間を引き継がない](https://www.authlete.com/ja/kb/oauth-and-openid-connect/refresh-tokens/refreshing-refre …

[check] JWT再チェック

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/friend.js
docker/srcs/uwsgi-django/accounts/templates/accounts/user_info.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/UserInfo.js
docker/srcs/uwsgi-django/trans_pj/tests/test_friend.py

#212 
- User Info pageのfriend deleteリンクが機能していなかった点を修正
- friend関係の操作をhth-button化

[fix] User Info: friend Deleteが機能しない

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/logout.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/online-status.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/setOnlineStatus.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js

<br>
```
Uncaught ReferenceError: handleClose is not defined
at socket.onclose (online-status.js:25:28)
```

Fix #146 & onlineStatusリファクタリング

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/logout.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/accounts/templates/accounts/login.html
docker/srcs/uwsgi-django/accounts/templates/accounts/signup.html
docker/srcs/uwsgi-django/accounts/views/two_factor_auth.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextUrl.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

#217 
```
Uncaught ReferenceError: loginUser is not defined
at HTMLFormElement.onsubmit (login/:1:1)
onsubmit @ login/:1
```
```
signup/:1 Uncaught ReferenceError: signupUser is not defined
at HTMLFormElement.onsubmit (signup/:1:1)
onsubmit @ signup/:1
```
- Guest用のLoginへのリダイレクト時(django viewによる描画)のみ`setupLoginEventListener()`を呼び出す必要がある（ルーターを介さずLoginを描画する=LoginEventListenerを設定できないため）
- guest用のnextURLを取得する関数内で、loginへのリダイレクトを判定し、必要に応じ`setupLoginEventListener()`を呼び出すことで対応
<hr>
流れで...
<hr>
- Guest
- 以下pathへのアクセス -> そのpathに移動
- それ以外 -> `/auth/login/`に遷移（URLも） -> login後は必ずtop `/app/`に遷移（loginリダイレクト前のページは無視）
https://github.com/42trans/ft_transcendence/blob/0af961e82b8050e89558bc5ec2ee1249acc35555/docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js#L18-L22
- User
- 以下pathへのアクセス …

[fix] log-in/sign-up時 console error

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongEngineKey.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameLoopManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameStateManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineIndex.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineRenderer.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineSyncWS.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/Game2D.js
docker/srcs/vite/pong-three/src/index.js

#223 
#227 
- 2Dの戻る、進むのバグ修正
- 戻る、進むの回数だけインスタンスが増えていく？。サーバーには複数のクライアントから同時にリクエスト => ボールが増える
- viewクラスでdispose()
- それをトリガーに、念の為、インスタンスとプロパティのnull埋めを全クラスで。
- eventListenerの廃棄
- 3Dと同様のロジックにOnlineIndex.jsを変更

2D戻る・進むのバグ、EventListenerの廃棄

---

docker/srcs/uwsgi-django/chat/dm_consumers.py
docker/srcs/uwsgi-django/chat/models.py
docker/srcs/uwsgi-django/chat/static/chat/js/dm-with-user.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/setup-dm-websocket.js
docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/chat/DMwithUser.js

#232 
- DM pageを複数回開くとsocketが重複し、メッセージの送信がバグる -> ページ離脱時にdisposeを追加
- 129文字以上のメッセージ送信でsocket closeされる対策  79855c9
- Message modelで129文字以上をNG判定 -> DM socket closeでDM継続不可になっていた
- 送信前のmessage長さチェックを追加しDM継続可能に
- 文字列長判定がオーバーフローしバグり、巨大文字列がDBに書き込まれることはなさそう
<br>
- JSのstring.lengthは`MAX_SAFE_INTEGER = 9007199254740991` までは精度を保証
-浮動小数点ラッパーの型のため、それ以上は正確に表現できなくなるが、オーバーフローはしない
<br>
- [MAX_SAFE_INTEGER](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

DM Socketのdispose 

---

docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/script.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/AbstractView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/Home.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Enable2FA.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Login.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Logout.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Signup.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Verify2FA.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/chat/DMSessions.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/chat/DMwithUser.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/FreePlay.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/Game2D.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/Game3D.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/GameMatch.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/PongTop.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/Tournament.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/ChangeAvatar.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/EditProfile.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/Friends.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/GameHistory.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/UserInfo.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/UserProfile.js

- `loadAndExecuteScript()`でDOMに追加した`<script>`を破棄できていなかった問題を解消
- 追加先を`document.body` -> `spaElement`に変更
```js
document.body.appendChild(scriptElement);
```
↓
```js
let spaElement = document.querySelector("#spa");
spaElement.innerHTML = htmlSrc;
spaElement.appendChild(scriptElement);
```

Fix spa append script

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/templates/accounts/login.html
docker/srcs/uwsgi-django/accounts/templates/accounts/signup.html
docker/srcs/uwsgi-django/accounts/views/basic_auth.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js

- Guest
- User
- b8e15b2
- 戻る/進む表示ページをgetNextPath()で取得し、guestであればルーターでloginに遷移するよう変更
<br>
- 履歴増殖はchrome拡張機能のバグだった模様？firefoxでは再現せず
- 必要なさそうであればマージ不要です

[fix] history, popstate

---

docker/srcs/uwsgi-django/pong/tournament/tests/test_tournament_data.py
docker/srcs/uwsgi-django/pong/urls_api.py
docker/srcs/uwsgi-django/pong/views/tournament_views.py
docker/srcs/uwsgi-django/trans_pj/tests/test_api_scurity.py

#248 
- Review用にAPIテストを集約（minimal security要件 第5項目の確認用）
- 実行：`docker exec uwsgi-django python manage.py test trans_pj.tests.test_api_scurity`
- `urls_api`に対するGET, POSTのresponseを確認。401（methodにより405も）が期待値
- `tournament/data/<int:tournament_id>/`はGuestも取得可能ですが、`IsAuthenticated`でも良さそうでしょうか？ -> `IsAuthenticated`に変更する場合は本ブランチで変更 & テスト変更後、マージします

[add] API test: 非認証者によるAPI GET/POSTの結果が401(or 405)であることを評価するテストを追加

---

docker/srcs/uwsgi-django/chat/consumers.py
docker/srcs/uwsgi-django/chat/dm_consumers.py
docker/srcs/uwsgi-django/chat/routing.py
docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/static/chat/js/dm-with-user.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/apply-message-style.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/handle-receive-message.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/setup-dm-websocket.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/ui-util.js
docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/chat/tests/test_dm_consumer.py
docker/srcs/uwsgi-django/chat/urls.py
docker/srcs/uwsgi-django/chat/views/get_dm_sessions.py
docker/srcs/uwsgi-django/chat/views/views.py
docker/srcs/uwsgi-django/pong/static/pong/css/hth-dm.css
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/routeTable.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/chat/DMwithUser.js
docker/srcs/uwsgi-django/trans_pj/static/spa/json/urlConfig.json
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_block.py
docker/srcs/uwsgi-django/trans_pj/tests/test_dm.py
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

#245 
<br>
- dm pageのURLは`nickname` -> `user_id`に変更
- nickname変更の影響を受けない状態になった
- URLが`/dm-with/<nickname>/`の場合、nicknameが変更されると画面更新後にDM維持できない
- DMwith画面表示の間、DM相手のnicknameは初期のまま固定（変更されても元のnicknameを使い続ける。updateしない）
- メッセージもuser_idベースとし、初期に読み込んだNicknameを送信者名として表示
- DMwith画面を更新すると、相手のnickname変更が反映される

[fix] DM: nickname変更の挙動

---

docker/srcs/uwsgi-django/accounts/templates/accounts/login.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/routeTable.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/cache.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/isUser.js
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

#267 
- Guest -> Log-in -> 42login -> TOP -> 戻るボタンでloginに戻る（login済みなのでTOPに遷移するはず）
- Guest -> Sign-up -> 42signup -> TOP -> 戻るボタンでsignupに戻る（login済みなのでTOPに遷移するはず）
<br>
- login, signup, oauthのキャッシュ管理を追加
- switchPage()でcacheを管理
- oauthで42サーバー接続前と思われる`/login`/, `/signup`/, (/`oauth-ft/`)のキャッシュ保持しないよう`setNoCache()`を呼び出し
- それ以外はキャッシュ保持に戻すため`clearNocache()`を呼び出し
- Login.jsなどの該当ページconstructor, disposeで呼び出すと、たまにlogin表示漏れるため、switchPage()で確実に実行
- DonContentLoadedのページ表示を`switchPage()` -> `renderView()`に変更
- 42authで42サーバーに移動するため、42auth後にDOMContentLoadedが呼ばれる 
- 42auth前後の戻る、進むでDOMContentLoadedが発火する
- login済みuserが`/login/`に戻る際、topに切り替わるが、switchPage()にすると履歴を上書きするため、URLのみ変更する`history.replaceState()` -> `renderView()`の呼び出しとした
- `updateHeader()`の追加呼び出しは不要そうだが、不安定ならrenderView()のどこかで呼び出すよう変更する
<br>
- …

[fix] 42authログイン後戻る->logiin表示 & header更新

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/friend.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/online-status.js
docker/srcs/uwsgi-django/accounts/templates/accounts/user_info.html
docker/srcs/uwsgi-django/accounts/tests/test_valid_user_id.py
docker/srcs/uwsgi-django/accounts/urls.py
docker/srcs/uwsgi-django/accounts/urls_api.py
docker/srcs/uwsgi-django/accounts/views/user.py
docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/chat/tests/test_valid_dm_user_id.py
docker/srcs/uwsgi-django/chat/urls.py
docker/srcs/uwsgi-django/chat/urls_api.py
docker/srcs/uwsgi-django/chat/views/views.py
docker/srcs/uwsgi-django/pong/tournament/tests/test_valid_match_id.py
docker/srcs/uwsgi-django/pong/urls.py
docker/srcs/uwsgi-django/pong/urls_api.py
docker/srcs/uwsgi-django/pong/views/navi_views.py
docker/srcs/uwsgi-django/pong/views/tournament_views.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/routeTable.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/utility/isValidParam.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/chat/DMwithUser.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/user/UserInfo.js
docker/srcs/uwsgi-django/trans_pj/static/spa/json/urlConfig.json
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_block.py
docker/srcs/uwsgi-django/trans_pj/tests/test_friend.py
docker/srcs/uwsgi-django/trans_pj/tests/test_url_access.py

- URLの検証を追加しました。不正なURL, parameterであれば`/app/`に画面、URL共に遷移するようになっていると思います
- ルーター周りの負債が蓄積してきた感が否めません...他の最低限の要件を確実にクリアしてから、リファクタリングしたいと思っています
- PRの新規実装・変更が2-300行、テストが300行程度だと思います。テスト追加＆修正で変更が大きめに出ています。
- 主な検証パラメータはAPIテストに記載しています 1563c3a bc968a5 41fd87c
<br>
- `/url/:intParam/`に文字列で表示バグ（`/app/game/match/hoge/`, `/app/dm/hoge/`）
- Djangoのルーティングでintが期待されているため、文字列の入力で404に飛ばされているらしい
- `int` -> `str`とし、`int(intParam)`の変換で整数でなければtopに飛ばすなどの処理を追加。とりあえず何かしら表示されるようになった。 b502189
- djangoのviewで遷移するとルーター経由しないため、表示内容やURLに不整合が生じる。getSelectedRoute()でパラメータの整合性を評価し、不正なURLの場合 `/app/invalid/` -> `/app/` に変更  4c150e6
- UserInfo: userIdの判定  a4de784
- DM: dmUserIdの判定  0376e60
- Tournament: matchIdの判定  2444a6e
<br>
- `/app/invalid-url/` -> `/app/`
- routeTableにマッチしない不正なURLは`getNextPath()`でtopを返すよう変更。不正なURLの場合は`getSele …

[fix] invalid URL

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameLoopManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineRenderer.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/TournamentMain.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentCreator.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentDeleter.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentEntry.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentOverview.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/RoundManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/UserManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateBaseRound.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateEntry.js
docker/srcs/uwsgi-django/pong/templates/pong/plane/bootstrap_index.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/bootstrap_sign-in.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/error.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/game_tmp.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/index copy.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/index.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/results.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/sign-in.html
docker/srcs/uwsgi-django/pong/templates/pong/plane/sign-up.html
docker/srcs/vite/pong-three/src/js/state/EntryGameState.js

e2e待ちで、前回の延長で行っています。
https://github.com/42trans/ft_transcendence/pull/280
前回プルリクがマージされていないので、変更に含まれています。
ここから２回分が実質の変更点です
https://github.com/42trans/ft_transcendence/pull/285/commits/5cff30a1c169b5d175d33af821ab6c59b84c023a
というか、それはコメントアウトしただけなので、
見てほしいコードはここだけ。２箇所にisvalid()メソッドを追加して毎行if(isValid)した
https://github.com/42trans/ft_transcendence/pull/285/commits/fe356fb0ff5d7ee611bcd3878a4dc4efca9561b1
#284 
問題：最後のloopでnullが入る
理由：3D同様、spaのイベントでdispose()が走るため非同期でnullが先に入る
修正前状況：雑にリセットで対処されてたので要件的にはOK
修正後：毎行nullチェックを行い、console.warn()してreturnする処理。リセットはしない

#280の後：本日プルリク２回目的なもの:endBtnにnulllのバグある

---

docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentCreator.js
docker/srcs/uwsgi-django/trans_pj/tests/test_tournament.py

E2E TestでTournament作成エラー時のアラート処置を追加 & 関連箇所の修正
- `_trimTournamentName()`を追加  5097650
-  `_getNicknames()`同様、trimする関数
- `      aaa` などの入力に対し、validate関数ではtrimした`aaa`を元に判定するが、API POSTの際にはtrimされていない`      aaa`で渡されるため、Tournament modelのValidationErrorが発生していた
- alertのエラーメッセージ表示 & E2Eでメッセージを検証  3e7d983

[fix] E2E & tournament

---

Makefile

- viteはbuildして、即down
- nginx, Django, Postgresのみ常時起動
- それに合わせてdownも修正
- make で build_up_defaultをそのまま呼び出すことにした

`make`コマンドでvite_buildもstaticも一発起動

---

docker/srcs/uwsgi-django/accounts/tests/test_valid_user_id.py
docker/srcs/uwsgi-django/accounts/views/user.py
docker/srcs/uwsgi-django/chat/tests/test_valid_dm_user_id.py
docker/srcs/uwsgi-django/chat/views/views.py
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/pong/tournament/tests/test_valid_match_id.py
docker/srcs/uwsgi-django/pong/views/tournament/is_valid_match_api_view.py
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getMatchedRoute.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js

- pathパラメータの比較を最小限とした
- 文字列操作系のためテストでバグチェックしたかったが、JSで関数単体テストを作成するハードルが高く、dev-linkにpath-testを埋め込み目視確認
- parameter検証APIの400 -> 200に変更
- consoleの400エラーを握り潰せなかったため、invalid parameterでも200を返すように変更（is_valid=Falseを返すため問題なし）
- 課題要件securityに則り、guestの場合は401を返す

pathマッチング修正

---

docker/srcs/uwsgi-django/accounts/templates/accounts/edit_profile.html
docker/srcs/uwsgi-django/accounts/tests/test_user_profile.py
docker/srcs/uwsgi-django/accounts/views/user.py

#332 
edit profileで変更後、profileに戻ってきた時点でエラー発生
```
Uncaught ReferenceError: updateNickname is not defined
onsubmit https://localhost/app/user/profile/edit/:1
edit:1:1
Uncaught ReferenceError: updatePassword is not defined
onsubmit https://localhost/app/user/profile/edit/:1
edit:1:1
```

update nickname, password後のuncaugth ReferenceError

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/accounts/tests/test_2fa.py
docker/srcs/uwsgi-django/accounts/tests/test_jwt.py
docker/srcs/uwsgi-django/accounts/tests/test_login.py
docker/srcs/uwsgi-django/accounts/tests/test_signup.py
docker/srcs/uwsgi-django/accounts/views/basic_auth.py
docker/srcs/uwsgi-django/accounts/views/oauth.py
docker/srcs/uwsgi-django/accounts/views/two_factor_auth.py
docker/srcs/uwsgi-django/trans_pj/tests/test_api_scurity.py
docker/srcs/uwsgi-django/trans_pj/tests/test_basic_auth.py

- 42signup nickname重複対策
- ランダムな0-9 x 5文字をsuffixとしたnicknameでユーザー登録（10000回トライ）   08a165d
```python
random_suffix = self._random_digit(5)
nick = f"{nickname}{random_suffix}"
```
- ユーザー数の上限10000なので十分なはず（作成失敗してもsignup遷移するだけ）
- 42auth->42emailでuserの存在評価するため、basic signupで42emailを禁止する（42emailでuser作成したければ42auth使ってね） d40b745
- 42emailのテスト追加
* ついでに
* signup, login, 2FAで不正値入力の際に400->200へ変更
* signup, login, 2FAで不正値入力の際のconsole.error削除
<br>
42signup（42nicknameに重複がなかった場合）
42signup（別のuserがすでにtakiraを使っていた場合）
signupで42email使用不可に
42authではemailベースでuser検索するため、別userが42email使用済みだと42signup不可 & そのuserとして42loginできてしまうため

42signup nickname重複時のエラーハンドリング & 400握り潰し

---

docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/views/views.py

- console error -> message-areaへの表示に変更
```
tournamentInvite(): error Error: The specified user does not exist
at dm-sessions.js:135:31
(anonymous) @ dm-sessions.js:151
Promise.catch (async)
tournamentInviteButton.onclick @ dm-sessions.js:150Understand this error
```
- validate-dm-targetの400->200

tournamentInviteのerror抑制

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/friend.js
docker/srcs/uwsgi-django/accounts/tests/test_friend.py
docker/srcs/uwsgi-django/accounts/views/friend.py

- お互いが削除 or 複数ページで操作し、操作が競合するとエラー & ページ更新,遷移しない限り同じリンクが表示され続けるため、switchPage(window.location.pathname)で画面更新するよう変更
- API操作リンクをhth btnスタイルに変更
- API400->200
before
after

FriendRequest
