42trans/ft_transcendence

.gitignore

- 昨日の修正の修正です。rootのstatic/だけgitignoreしたいのに、全部のstatic/が設定されてた。

🐝✅.gitignore: static/ => /static/

---

docker/srcs/uwsgi-django/trans_pj/tests/__init__.py

fix: E2E signup時のtimeout対策

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameLoopManager.js
docker/srcs/uwsgi-django/pong/templates/pong/pong-online.html

https://github.com/42trans/ft_transcendence/issues/143
- あらかじめ.htmlにボタンを用意しておき、非表示・表示、DOM削除で対応する

[bugfix]2D-Pong: start,engGame Button

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameLoopManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameStateManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineIndex.js
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineSyncWS.js
docker/srcs/uwsgi-django/pong/templates/pong/pong-online.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js

詳細は #144
[bugfix]2D-Pongページ表示中にnaviから同ページを呼び出した際、startBtnが機能しない、EndGameBtnが残り続けるバグの修正

EndBtnのバグ#144

---

docker/srcs/uwsgi-django/trans_pj/tests/__init__.py

- 現象
- signupのemail, nickname入力が不安定？ #128 
- 成功時には3min程度でテストpass
- 失敗時にはinput要素が見つからずエラー or timeout
- 原因
- リンククリックによる遷移後、emailなどのinput要素の取得に失敗 -> input要素へ入力できずタイムアウトになっていた
- local(mac, Linux)では安定、github actionsでは不安定な理由は不明
- 対策
- 要素取得前に確実にページ遷移している状態にするため、リンククリック遷移後`wait_to_be_url()`で期待するURLに遷移するまで待機処理を追加
<br>
本ブランチ内では安定した結果が得られるようになったため、devで様子見する

[fix] E2EテストのFail対策

---

docker/srcs/uwsgi-django/trans_pj/templates/base.html
docker/srcs/uwsgi-django/trans_pj/templates/footer.html

#109 
仮ですが、footer linkをTOP, 2D-Pong, 3D-Pongとしています

[fix] footer linkを/app/に変更

---

docker/srcs/uwsgi-django/chat/static/chat/js/dm-sessions.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/handle-receive-message.js
docker/srcs/uwsgi-django/chat/templates/chat/dm_with.html
docker/srcs/uwsgi-django/chat/views/views.py
docker/srcs/uwsgi-django/trans_pj/tests/test_dm.py

#152 
`<script>alert("hello")</script>`などの入力を文字列として解釈するよう修正

[fix] DM XSS対策

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-header.css
docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/trans_pj/templates/footer.html
docker/srcs/uwsgi-django/trans_pj/templates/header.html
docker/srcs/uwsgi-django/trans_pj/templates/lang_test.html
docker/srcs/uwsgi-django/trans_pj/templates/script1.html
docker/srcs/uwsgi-django/trans_pj/templates/script2.html
docker/srcs/uwsgi-django/trans_pj/tests/test_top.py
docker/srcs/vite/pong-three/src/css/3d.css
docker/srcs/vite/pong-three/src/index.html
docker/srcs/vite/pong-three/src/js/manager/AllScenesManager.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineInit.js

#161 
3Dのフッターが見えなくなる。仕様とする？
ナビが多くてブレークポイントと合ってない。減らすかトグル化を早める
SS-Pong: ヘッダーフッターに覆い被さる範囲のコントロール
3D: 全画面表示でも違和感ないUX
モバイルの幅と高さの崩れチェック
現行製品が360px以上であることの論拠

#161: SPA化: navi, 2D,3D描画領域

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-header.css
docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/trans_pj/templates/footer.html
docker/srcs/uwsgi-django/trans_pj/templates/header.html
docker/srcs/uwsgi-django/trans_pj/templates/lang_test.html
docker/srcs/uwsgi-django/trans_pj/templates/script1.html
docker/srcs/uwsgi-django/trans_pj/templates/script2.html
docker/srcs/uwsgi-django/trans_pj/tests/test_top.py
docker/srcs/vite/pong-three/src/css/3d.css
docker/srcs/vite/pong-three/src/index.html
docker/srcs/vite/pong-three/src/js/manager/AllScenesManager.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineInit.js

Ui-after-spa-#154

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineClientApp.js
docker/srcs/uwsgi-django/pong/templates/pong/dev-link.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/templates/base.html
docker/srcs/uwsgi-django/trans_pj/templates/footer.html
docker/srcs/uwsgi-django/trans_pj/templates/header.html
docker/srcs/uwsgi-django/trans_pj/templates/lang_test.html
docker/srcs/uwsgi-django/trans_pj/templates/script1.html
docker/srcs/uwsgi-django/trans_pj/templates/script2.html
docker/srcs/uwsgi-django/trans_pj/templates/theme-toggle.html
docker/srcs/uwsgi-django/trans_pj/tests/test_top.py

#159 
ルーターのコードの理解と違う。ので、別枠で見てほしい。
意図：
コードはドロップダウンメニュー以外のリンクには反応しないようにしている
挙動：
しかし、全て正常に遷移する。期待する挙動になっている。
仮説：
SPA関連の何かの設定で、上書きされている？

トグルdropdownメニュー: 挙動はOKなのだが、意図とは違う

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/logout.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/updateHeader.js
docker/srcs/uwsgi-django/trans_pj/urls.py
docker/srcs/uwsgi-django/trans_pj/views/main_views.py
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineMatch.js

#185 のmerge先を誤りdevになっていなかったので、devへmergeする & 記録用
PR詳細は#185参照

[subject] SPA #185 -> dev merge用

---

docker/srcs/vite/pong-three/src/js/pongEngine/PongEngine.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineData.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineInit.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineMatch.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineUpdate.js
docker/srcs/vite/pong-three/src/js/state/GamePlayState.js

3D-bug-#190

---

docker/srcs/uwsgi-django/pong/static/pong/js/tournament/TournamentMain.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/UserManager.js

#134
処理順に手前から３ファイル。これでキャッチはするはず。細かいdebugには不親切ですが、ハンドリングの有無だけで言えば、している。というディフェンスが可能なはず。

[add]try-cacth: tournament　mainで包括的にキャッチ。細かいところは余力あれば。一旦spaへ。

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/pong/templates/pong/game.html
docker/srcs/uwsgi-django/pong/templates/pong/play-tournament.html
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/vite/pong-three/src/js/pongEngine/PongEngineMatch.js
docker/srcs/vite/pong-three/src/js/state/EntryGameState.js

https://github.com/42trans/ft_transcendence/issues/178
プルリク忘れてた？3Dgameのボタンのバグの修正

ボタンのバグ修正のプルリク忘れてた？ので3Dbtn-#194

---

docker/srcs/uwsgi-django/accounts/views/user.py

#82 
- Tournament開催中(is_finish = False)は、organizerのnicknameを変更不可にする
- organizerはTournament作成時点のnicknameでゲーム登録するため
- 履歴をplayer nameで追跡しない、紐付けしていないため、今のところあまり意味はないかも

nickname変更タイミング

---

docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/vite/pong-three/src/index.js
docker/srcs/vite/pong-three/src/js/PongApp.js
docker/srcs/vite/pong-three/src/js/effect/Aura.js
docker/srcs/vite/pong-three/src/js/effect/Flare.js
docker/srcs/vite/pong-three/src/js/effect/FlareEmitter.js
docker/srcs/vite/pong-three/src/js/effect/MagmaFlare.js
docker/srcs/vite/pong-three/src/js/effect/TextureCache.js
docker/srcs/vite/pong-three/src/js/effect/ZoomBall.js
docker/srcs/vite/pong-three/src/js/manager/AnimationMixersManager.js
docker/srcs/vite/pong-three/src/js/manager/GameStateManager.js
docker/srcs/vite/pong-three/src/js/manager/LoopManager.js
docker/srcs/vite/pong-three/src/js/manager/RendererManager.js
docker/srcs/vite/pong-three/src/js/state/EntryGameState.js

連戦時の再描画のバグ修正完了。まだ戻る>進むでバグ

---

docker/srcs/uwsgi-django/trans_pj/static/spa/js/index.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/renderView.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/GameMatch.js
docker/srcs/vite/pong-three/src/js/state/EntryGameState.js

#194 
- window.dispatchEvent(new CustomEvent('switchPageResetState'));をrenderView内部に移動
- バグ？
index.jsが増えていく　見た目もplayも問題なし。
discordに動画あげときます　
コンソールのスクショは #194 コメントに

3D再描画：戻る>進む

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineIndex.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/pong/GameMatch.js
docker/srcs/vite/pong-three/src/index.js
docker/srcs/vite/pong-three/src/js/PongApp.js

再発：3D連戦、戻る進む & EventListerner削除

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/enable_2fa.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/login.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/signup.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/userProfile.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/verify_2fa.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/routing/getNextPath.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Enable2FA.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Login.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Signup.js
docker/srcs/uwsgi-django/trans_pj/static/spa/js/views/auth/Verify2FA.js

form, button要素だから意味なかった？
<br>
重複設定を修正

[EventListener見直し] Auth

---

docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameStateManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateBaseRound.js
docker/srcs/uwsgi-django/pong/views/tournament_views.py
docker/srcs/vite/pong-three/src/js/manager/AllScenesManager.js

resize bugfix

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/pong/static/pong/js/online/PongOnlineGameLoopManager.js
docker/srcs/uwsgi-django/pong/templates/pong/pong-online.html

- 初回ボールサーブ2秒待機

---

docker/srcs/uwsgi-django/pong/static/pong/js/tournament/TournamentMain.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentCreator.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentDeleter.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentEntry.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/components/TournamentOverview.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/RoundManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/TournamentManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/manager/UserManager.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateBaseRound.js
docker/srcs/uwsgi-django/pong/static/pong/js/tournament/round/StateEntry.js
docker/srcs/vite/pong-three/src/js/state/EntryGameState.js

#271
エラーハンドリングをリセットにする処理で、e2eテストがずれたかも。

#271-catch-reset-tournament

---

docker/srcs/uwsgi-django/chat/tests/test_dm_consumer.py
docker/srcs/uwsgi-django/chat/views/system_message.py
docker/srcs/uwsgi-django/pong/views/tournament/save_views.py
docker/srcs/uwsgi-django/pong/views/tournament/signals.py

イベントドリブンtournament開催告知: 

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py

プログレスバーをボタンの後に。z-index

---

docker/srcs/uwsgi-django/pong/static/pong/css/hth-online.css

#301
CSSだけ。レイアウトやサイズは変えず。色や形、z-indexの見た目だけ。

間に合えば。CSS ちょっとした見栄えを。slideupText

---

docker/srcs/uwsgi-django/accounts/templates/accounts/user_info.html

UserInfoPage

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/block-user.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/unblock-user.js
docker/srcs/uwsgi-django/accounts/templates/accounts/user_info.html
docker/srcs/uwsgi-django/accounts/tests/test_block.py
docker/srcs/uwsgi-django/accounts/urls_api.py
docker/srcs/uwsgi-django/accounts/views/block.py

- nickname -> user idベースに変更
- #357 同様、複数ページを開き操作が競合するとエラー & ページ更新,遷移しない限り同じリンクが表示され続けるため、switchPage(window.location.pathname)で画面更新するよう変更
- API 400->200

Fix block user

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/enable_2fa.js
docker/srcs/uwsgi-django/accounts/views/two_factor_auth.py
docker/srcs/uwsgi-django/trans_pj/tests/__init__.py
docker/srcs/uwsgi-django/trans_pj/tests/test_2fa.py

- 2画面でenable2faを開き、画面1で2FA有効化したのち画面2で有効化すると、画面2はtopに飛ばされる
- 遷移先をTOP -> Profileに変更  e47be77
<br>
- 2画面でenable2faを開き、画面1でlogoutしたのち画面2で2FA有効化すると、401で画面に止まる
- alert + TOP遷移に変更  1be5c90

すでに有効な2FAを有効化しようとした時の挙動修正

---

docker/srcs/uwsgi-django/accounts/static/accounts/js/friend.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/history.js
docker/srcs/uwsgi-django/accounts/static/accounts/js/userProfile.js
docker/srcs/uwsgi-django/accounts/templates/accounts/user.html
docker/srcs/uwsgi-django/accounts/templates/accounts/user_info.html
docker/srcs/uwsgi-django/pong/static/pong/css/hth-accounts.css
docker/srcs/uwsgi-django/pong/static/pong/css/hth-animation.css
docker/srcs/uwsgi-django/pong/static/pong/css/hth-dm.css

- ついでにDM session Listの　li で不要な箇所から 箇条書きマーク"・"を外す　list-style: none;

#361-slideupText

---

docker/srcs/uwsgi-django/chat/static/chat/js/module/apply-message-style.js
docker/srcs/uwsgi-django/chat/static/chat/js/module/handle-receive-message.js
docker/srcs/uwsgi-django/pong/static/pong/css/hth-main.css
docker/srcs/uwsgi-django/trans_pj/static/spa/css/spa.css

#371
- DMのコーナーケースがわからないのでテストしてほしい
- 普通のケースでは動いてます。

#371-DM-LocalTZ
